const postsData = [
    { name: "Elena García", location: "Jalisco", text: "Me comprometo a separar la basura en mi casa y fomentar el reciclaje en mi comunidad." },
    { name: "Carlos Rodríguez", location: "Nuevo León", text: "No volveré a estacionarme en lugares para discapacitados. Respetaré los espacios asignados." },
    { name: "Sofía Martínez", location: "Puebla", text: "Me comprometo a verificar las noticias antes de compartirlas para no difundir información falsa." },
    { name: "Miguel Hernández", location: "Yucatán", text: "Cuidaré el agua en todas mis actividades diarias, cerrando la llave cuando no la use." },
    { name: "Ana López", location: "Chihuahua", text: "Seré voluntaria en un refugio de animales local una vez al mes." },
    { name: "Javier Pérez", location: "Veracruz", text: "Me comprometo a usar menos plástico, llevando siempre mis bolsas reutilizables al supermercado." },
    { name: "Laura Gómez", location: "Guanajuato", text: "Denunciaré cualquier acto de corrupción que presencie, sin importar cuán pequeño sea." },
    { name: "David Díaz", location: "Sinaloa", text: "Respetaré los límites de velocidad y las señales de tránsito para la seguridad de todos." },
    { name: "Mariana Sánchez", location: "Baja California", text: "Compraré productos locales para apoyar a los pequeños comerciantes de mi ciudad." },
    { name: "Fernando Morales", location: "Estado de México", text: "Me comprometo a ser un peatón responsable, cruzando siempre por las cebras peatonales." },
    { name: "Valeria Castillo", location: "Querétaro", text: "Participaré activamente en las juntas de vecinos para mejorar mi colonia." },
    { name: "Ricardo Romero", location: "Hidalgo", text: "No tiraré basura en la calle y recogeré la que encuentre a mi paso si es posible." },
    { name: "Paola Flores", location: "Sonora", text: "Me comprometo a tratar a todas las personas con amabilidad y respeto, sin importar sus diferencias." },
    { name: "Jorge Ortiz", location: "Coahuila", text: "Ahorraré energía eléctrica en casa, apagando las luces y desconectando aparatos que no uso." },
    { name: "Daniela Cruz", location: "Tabasco", text: "Cederé mi asiento en el transporte público a personas mayores, embarazadas o con discapacidad." },
    { name: "Alejandro Reyes", location: "San Luis Potosí", text: "Plantare un árbol cada año para contribuir al medio ambiente de mi ciudad." },
    { name: "Gabriela Navarro", location: "Michoacán", text: "Me informaré sobre mis derechos y obligaciones como ciudadano para participar de forma más activa." },
    { name: "Francisco Torres", location: "Oaxaca", text: "Me comprometo a no participar ni fomentar chismes o rumores que dañen a otras personas." },
    { name: "Mónica Vargas", location: "Tamaulipas", text: "Donaré sangre de forma regular para ayudar a quienes lo necesitan." },
    { name: "Eduardo Jiménez", location: "Guerrero", text: "Seré un tutor para un estudiante de primaria que necesite ayuda con sus tareas." },
    { name: "Beatriz Mendoza", location: "Zacatecas", text: "Adoptaré una mascota de un refugio en lugar de comprarla." },
    { name: "Raúl Guerrero", location: "Aguascalientes", text: "Respetaré y cuidaré los parques y áreas verdes de mi ciudad como si fueran mi propio jardín." },
    { name: "Isabel Ríos", location: "Morelos", text: "Aprenderé primeros auxilios para poder ayudar en caso de una emergencia." },
    { name: "Arturo Paredes", location: "Nayarit", text: "Fomentaré el diálogo y la resolución pacífica de conflictos en mi entorno." },
    { name: "Verónica Castro", location: "Tlaxcala", text: "Me comprometo a ser puntual en todas mis citas y reuniones como señal de respeto al tiempo de los demás." }
];
